import fs from 'fs'
import path from 'path'
import { Request, Response, NextFunction } from 'express'
import { Types } from 'mongoose'
import { Donation } from '../models/donation'
import { DonationUser } from '../models/user'
import { DonationRequest } from '../middleware/donationAuth'
import { HttpError } from '../errors'

function userId(request: Request) { return (request as DonationRequest).donationUser!.id }
function validatePan(value: unknown) { return typeof value === 'string' && /^[A-Z]{5}[0-9]{4}[A-Z]$/.test(value.trim().toUpperCase()) }

export async function collectorStatus(request: Request, response: Response, next: NextFunction) { try { const user = await DonationUser.findById(userId(request)).select('fullName mobile referralCode role collectorProfile'); if (!user) throw new HttpError(404, 'User not found'); const profile = user.collectorProfile ? { fullName: user.collectorProfile.fullName, status: user.collectorProfile.status, submittedAt: user.collectorProfile.submittedAt, approvedAt: user.collectorProfile.approvedAt, rejectedReason: user.collectorProfile.rejectedReason } : null; response.json({ success: true, data: { collectorId: String(user._id), fullName: user.fullName, mobile: user.mobile, referralCode: user.referralCode, role: user.role, collectorProfile: profile } }) } catch (error) { next(error) } }

export async function applyCollector(request: Request, response: Response, next: NextFunction) { try { const { fullName, address, panNumber } = request.body ?? {}; if (!fullName || !address || !validatePan(panNumber)) throw new HttpError(400, 'Full name, address, and valid PAN are required'); const user = await DonationUser.findById(userId(request)); if (!user) throw new HttpError(404, 'User not found'); if (user.role !== 'USER' || user.collectorProfile?.status === 'pending') throw new HttpError(400, 'User is not eligible to apply'); const files = (request as any).files as Express.Multer.File[] | undefined; if (!files?.some((file) => file.fieldname === 'aadharFront') || !files.some((file) => file.fieldname === 'aadharBack')) throw new HttpError(400, 'Both Aadhar front and back images are required'); const dir = path.join(process.cwd(), 'backend', 'private_storage', 'kyc'); await fs.promises.mkdir(dir, { recursive: true }); const saved: Record<string, string> = {}; for (const file of files) { const key = `kyc_${user._id}_${Date.now()}_${file.fieldname}${path.extname(file.originalname)}`; await fs.promises.writeFile(path.join(dir, key), file.buffer); saved[file.fieldname] = key } user.fullName = String(fullName).trim(); user.role = 'COLLECTOR_PENDING'; user.collectorProfile = { fullName: String(fullName).trim(), address: String(address).trim(), panNumber: String(panNumber).trim().toUpperCase(), aadharFront: { fileKey: saved.aadharFront, uploadedAt: new Date() }, aadharBack: { fileKey: saved.aadharBack, uploadedAt: new Date() }, status: 'pending', submittedAt: new Date() } as any; await user.save(); response.json({ success: true, message: 'Collector application submitted successfully.' }) } catch (error) { next(error) } }

export async function collectorDashboard(request: Request, response: Response, next: NextFunction) { try { const id = new Types.ObjectId(userId(request)); const stats = await Donation.aggregate([{ $match: { collectorId: id, hasCollectorAttribution: true, status: 'SUCCESS' } }, { $group: { _id: null, totalAmount: { $sum: '$amount' }, donationCount: { $sum: 1 } } }]); const user = await DonationUser.findById(id).select('fullName referralCode').lean(); const recent = await Donation.find({ collectorId: id, hasCollectorAttribution: true, status: 'SUCCESS' }).sort({ createdAt: -1 }).limit(10).select('donor amount donationHead createdAt').lean(); response.json({ success: true, data: { referralCode: user?.referralCode ?? null, collectorName: user?.fullName ?? null, totalAmount: stats[0]?.totalAmount ?? 0, donationCount: stats[0]?.donationCount ?? 0, recentDonations: recent.map((d: any) => ({ donorName: d.donor.anonymousDisplay ? 'Anonymous' : d.donor.name, amount: d.amount, cause: d.donationHead.name, date: d.createdAt })) } }) } catch (error) { next(error) } }

export async function leaderboard(request: Request, response: Response, next: NextFunction) { try { const limit = Math.min(Number(request.query.limit ?? 5) || 5, 20); const data = await Donation.aggregate([{ $match: { collectorId: { $ne: null }, hasCollectorAttribution: true, status: 'SUCCESS' } }, { $group: { _id: '$collectorId', collectorName: { $last: '$collectorName' }, totalAmount: { $sum: '$amount' }, donationCount: { $sum: 1 } } }, { $sort: { totalAmount: -1 } }, { $limit: limit }]); response.json({ leaderboard: data.map((d, i) => ({ rank: i + 1, collectorId: d._id, collectorName: d.collectorName ?? 'Unknown Collector', totalAmount: d.totalAmount, donationCount: d.donationCount })) }) } catch (error) { next(error) } }
