import { Router } from 'express'
import { Donation } from '../models/donation'
import { DonationHead } from '../models/donationHead'
import { DonationUser } from '../models/user'
import { requireDonationAuth, DonationRequest } from '../middleware/donationAuth'
import { HttpError } from '../errors'

function admin(request: DonationRequest) { if (!['SYSTEM_ADMIN', 'WEBSITE_ADMIN'].includes(request.donationUser?.role ?? '')) throw new HttpError(403, 'Administrator access required') }
export const donationAdminRouter = Router()
donationAdminRouter.use(requireDonationAuth)
donationAdminRouter.get('/donations', async (request, response, next) => { try { admin(request as DonationRequest); const data = await Donation.find().sort({ createdAt: -1 }).limit(100).lean(); response.json({ donations: data }) } catch (error) { next(error) } })
donationAdminRouter.post('/donations/cash', async (request, response, next) => { try { admin(request as DonationRequest); const { donor, donationHead, amount, paymentMethod, transactionRef } = request.body ?? {}; const donation = await Donation.create({ donor, donationHead, amount, paymentMethod: paymentMethod ?? 'CASH', status: 'SUCCESS', transactionRef, addedBy: (request as DonationRequest).donationUser!.id }); response.status(201).json({ donation }) } catch (error) { next(error) } })
donationAdminRouter.post('/donations/offline', async (request, response, next) => { try { admin(request as DonationRequest); const { donor, donationHead, amount, paymentMethod, transactionRef } = request.body ?? {}; const donation = await Donation.create({ donor, donationHead, amount, paymentMethod: paymentMethod ?? 'CASH', status: 'SUCCESS', transactionRef, addedBy: (request as DonationRequest).donationUser!.id }); response.status(201).json({ donation }) } catch (error) { next(error) } })
donationAdminRouter.get('/collectors', async (request, response, next) => { try { admin(request as DonationRequest); response.json({ collectors: await DonationUser.find({ referralCode: { $ne: null } }).select('-emailVerificationToken -emailVerificationExpiry').lean() }) } catch (error) { next(error) } })
donationAdminRouter.get('/collectors/summary', async (request, response, next) => { try { admin(request as DonationRequest); response.json({ collectors: await DonationUser.countDocuments({ referralCode: { $ne: null } }), approved: await DonationUser.countDocuments({ role: 'COLLECTOR_APPROVED' }) }) } catch (error) { next(error) } })
donationAdminRouter.get('/collectors/:id', async (request, response, next) => { try { admin(request as DonationRequest); const user = await DonationUser.findById(request.params.id).select('-emailVerificationToken -emailVerificationExpiry'); if (!user) throw new HttpError(404, 'Collector not found'); response.json({ collector: user }) } catch (error) { next(error) } })
donationAdminRouter.patch('/collectors/:id/toggle-status', async (request, response, next) => { try { admin(request as DonationRequest); const user = await DonationUser.findById(request.params.id); if (!user) throw new HttpError(404, 'Collector not found'); user.collectorDisabled = !user.collectorDisabled; await user.save(); response.json({ success: true, collectorDisabled: user.collectorDisabled }) } catch (error) { next(error) } })
donationAdminRouter.get('/collector-applications', async (request, response, next) => { try { admin(request as DonationRequest); response.json({ applications: await DonationUser.find({ 'collectorProfile.status': { $in: ['pending', 'approved', 'rejected'] } }).select('-emailVerificationToken -emailVerificationExpiry').lean() }) } catch (error) { next(error) } })
donationAdminRouter.post('/collector/:userId/approve', async (request, response, next) => { try { admin(request as DonationRequest); const user = await DonationUser.findByIdAndUpdate(request.params.userId, { role: 'COLLECTOR_APPROVED', 'collectorProfile.status': 'approved', 'collectorProfile.approvedAt': new Date() }, { new: true }); response.json({ success: true, user }) } catch (error) { next(error) } })
donationAdminRouter.post('/collector/:userId/reject', async (request, response, next) => { try { admin(request as DonationRequest); const user = await DonationUser.findByIdAndUpdate(request.params.userId, { role: 'USER', 'collectorProfile.status': 'rejected', 'collectorProfile.rejectedReason': request.body?.reason ?? 'Rejected' }, { new: true }); response.json({ success: true, user }) } catch (error) { next(error) } })
donationAdminRouter.post('/collector/:userId/revoke', async (request, response, next) => { try { admin(request as DonationRequest); const user = await DonationUser.findByIdAndUpdate(request.params.userId, { role: 'USER', 'collectorProfile.status': 'rejected' }, { new: true }); response.json({ success: true, user }) } catch (error) { next(error) } })

export const donationHeadAdminRouter = Router()
donationHeadAdminRouter.use(requireDonationAuth)
donationHeadAdminRouter.use((request, _response, next) => { try { admin(request as DonationRequest); next() } catch (error) { next(error) } })
donationHeadAdminRouter.get('/', async (_request, response, next) => { try { response.json({ success: true, data: await DonationHead.find().sort({ order: 1 }) }) } catch (error) { next(error) } })
donationHeadAdminRouter.post('/', async (request, response, next) => { try { const data = await DonationHead.create(request.body); response.status(201).json({ success: true, data }) } catch (error) { next(error) } })
donationHeadAdminRouter.put('/reorder', async (request, response, next) => { try { const items = Array.isArray(request.body) ? request.body : request.body?.items; await Promise.all((items ?? []).map((item: any) => DonationHead.findByIdAndUpdate(item.id, { order: item.order }))); response.json({ success: true }) } catch (error) { next(error) } })
donationHeadAdminRouter.get('/:id', async (request, response, next) => { try { const data = await DonationHead.findById(request.params.id); if (!data) throw new HttpError(404, 'Donation head not found'); response.json({ success: true, data }) } catch (error) { next(error) } })
donationHeadAdminRouter.put('/:id', async (request, response, next) => { try { const data = await DonationHead.findByIdAndUpdate(request.params.id, request.body, { new: true, runValidators: true }); if (!data) throw new HttpError(404, 'Donation head not found'); response.json({ success: true, data }) } catch (error) { next(error) } })
donationHeadAdminRouter.delete('/:id', async (request, response, next) => { try { const data = await DonationHead.findByIdAndDelete(request.params.id); if (!data) throw new HttpError(404, 'Donation head not found'); response.json({ success: true }) } catch (error) { next(error) } })
donationHeadAdminRouter.patch('/:id/toggle', async (request, response, next) => { try { const data = await DonationHead.findById(request.params.id); if (!data) throw new HttpError(404, 'Donation head not found'); data.isActive = !data.isActive; await data.save(); response.json({ success: true, data: { isActive: data.isActive } }) } catch (error) { next(error) } })
donationHeadAdminRouter.post('/:id/sub-causes', async (request, response, next) => { try { const data = await DonationHead.findByIdAndUpdate(request.params.id, { $push: { subCauses: request.body } }, { new: true }); if (!data) throw new HttpError(404, 'Donation head not found'); response.status(201).json({ success: true, data }) } catch (error) { next(error) } })
donationHeadAdminRouter.delete('/:id/sub-causes/:subCauseId', async (request, response, next) => { try { const data = await DonationHead.findByIdAndUpdate(request.params.id, { $pull: { subCauses: { _id: request.params.subCauseId } } }, { new: true }); if (!data) throw new HttpError(404, 'Donation head not found'); response.json({ success: true, data }) } catch (error) { next(error) } })
