import { Router } from 'express'
import { Donation } from '../models/donation'
import { DonationHead } from '../models/donationHead'
import { DonationUser } from '../models/user'

function display(value: any) { return typeof value === 'string' ? value : value?.en ?? value?.hi ?? Object.values(value ?? {})[0] ?? '' }

export const donationPublicRouter = Router()
donationPublicRouter.get('/donation-heads', async (_request, response, next) => { try { const data = await DonationHead.find({ isActive: true }).sort({ order: 1 }).select('-createdBy -updatedBy -__v').lean(); response.json({ success: true, data }) } catch (error) { next(error) } })
donationPublicRouter.get('/donation-heads/featured', async (request, response, next) => { try { const limit = Math.min(Number(request.query.limit ?? 4) || 4, 20); const data = await DonationHead.find({ isActive: true, isFeatured: true }).sort({ order: 1 }).limit(limit).lean(); response.json({ success: true, data }) } catch (error) { next(error) } })
donationPublicRouter.get('/donation-heads/:key/stats', async (request, response, next) => { try { const head = await DonationHead.findOne({ key: String(request.params.key).toLowerCase(), isActive: true }).lean(); if (!head) return response.status(404).json({ success: false, message: 'Donation cause not found' }); const stats = await Donation.aggregate([{ $match: { status: 'SUCCESS', 'donationHead.key': head.key } }, { $group: { _id: null, totalAmount: { $sum: '$amount' } } }]); const totalAmount = stats[0]?.totalAmount ?? 0; response.json({ success: true, data: { key: head.key, name: display(head.name), goalAmount: head.goalAmount, totalAmount, percentageReached: head.goalAmount ? Math.min(100, Math.round(totalAmount / head.goalAmount * 100)) : null } }) } catch (error) { next(error) } })
donationPublicRouter.get('/donation-heads/:key', async (request, response, next) => { try { const data = await DonationHead.findOne({ key: String(request.params.key).toLowerCase(), isActive: true }).select('-createdBy -updatedBy -__v').lean(); if (!data) return response.status(404).json({ success: false, message: 'Donation cause not found' }); response.json({ success: true, data }) } catch (error) { next(error) } })
donationPublicRouter.get('/referral/:code', async (request, response) => { const collector = await DonationUser.findOne({ referralCode: String(request.params.code).toUpperCase(), collectorDisabled: { $ne: true } }).select('fullName collectorProfile.fullName').lean(); response.json(collector ? { valid: true, collectorName: collector.fullName ?? collector.collectorProfile?.fullName } : { valid: false }) })
donationPublicRouter.get('/donations/recent', async (_request, response, next) => { try { const donations: any[] = await Donation.find({ status: 'SUCCESS' }).sort({ createdAt: -1 }).limit(10).select('donor amount').lean(); response.json(donations.map((d, i) => ({ id: `recent-${i}`, name: d.donor.anonymousDisplay ? 'Anonymous' : d.donor.name, city: d.donor.addressObj?.city ?? 'India', amount: d.amount }))) } catch (error) { next(error) } })
donationPublicRouter.get('/donations/top', async (_request, response, next) => { try { const data = await Donation.aggregate([{ $match: { status: 'SUCCESS', 'donor.anonymousDisplay': { $ne: true } } }, { $group: { _id: '$donor.name', totalAmount: { $sum: '$amount' } } }, { $sort: { totalAmount: -1 } }, { $limit: 5 }, { $project: { _id: 0, name: '$_id', totalAmount: 1 } }]); response.json(data.map((d, i) => ({ id: i + 1, ...d }))) } catch (error) { next(error) } })
